#!/usr/bin/env ruby
at_exit{ exit $exitcode }

begin
	options = {}
	if ARGV.empty?
		puts `#{$0}  --help`
		$exitcode = 1
		exit
	end
	# настройки
	require_relative './config.rb'
	Config.start
	require_relative 'models/parser.rb'
	# параметры командной строки
	Parser.do
	options = Parser.options
	$logger.debug "команды: #{options.inspect}"
	# выполнить всё веленное
	Executor.add_changes!(options)
rescue ActiveRecord::RecordNotFound => e
	$logger.fatal "Запись не найдена в базе. #{e}"
end
