mysql:
    development:
        adapter: mysql2
        encoding: utf8
        pool: 25
        schema_search_path: timebay
        connect_timeout: 1500
        read_timeout: 1500
        write_timeout: 1500
        database: pjreq
        username: pjreq
        password: ababagalamaga
global:
    query_delay: 300 # интервал опроса исходников
    timeout: 30
dbsetup:
    log: #{STDERR}
appsetup:
    log: #{STDERR}
bigbro:
    log: log/bigbro-#{Time.now.strftime "%s"}
