mysql:
    default: &default
        adapter: mysql2
        encoding: utf8
        pool: 25
        connect_timeout: 1500
        read_timeout: 1500
        write_timeout: 1500
    development:
        <<: *default
        database: pjreq
        username: pjreq
        password: ababagalamaga
    test:
        <<: *default
        database: pjreq_test
        username: pjreq
        password: ababagalamaga
redis: 
    db: 0
    host: 127.0.0.1
global:
    query_delay: 30 # интервал опроса исходников
    timeout: 30
    cachedir: /home/dimytch/work/tmp/pjreq
dbsetup:
    log:  STDERR
appsetup:
    log:  STDERR
    publish: nodes.listing.yml
bigbro:
    log: log/bigbro.log
