mysql:
    default: &default
        adapter: mysql2
        encoding: utf8
        pool: 25
        connect_timeout: 1500
        read_timeout: 1500
        write_timeout: 1500
    development:
        <<: *default
        database: pjreq
        username: pjreq
        password: ababagalamaga
    test:
        <<: *default
        database: pjreq_test
        username: pjreq
        password: ababagalamaga
global:
    query_delay: 30 # интервал опроса исходников
    timeout: 30
    tmpdir: /tmp
dbsetup:
    log:  STDERR
appsetup:
    log:  STDERR
    publish: nodes.listing.yml
bigbro:
    log: log/bigbro-#{ Time.now.strftime "%s" }
