mysql:
  database: pjreq
  user: pjreq
  password: ababagalamaga
  # host:
  # port:
  # socket:
  # encoding:
  # timeout:
  # connect_timeout:
  # http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-mysql2
global:
  query_delay: 300 # интервал опроса исходников
